title: Tom Connole
description: Customer Experience Technologist & Journey Manager
baseurl: ""
url: https://tomconnole.com

collections:
  posts:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
